---
# tasks file for deploy-postgres

  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
    register: installed_pg

  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes

  - name: initilize postgres - initdb
    command: postgresql-setup initdb
    when: installed_pg.changed

  - name: initilize postgres - chkconfig
    command: chkconfig postgresql on
    when: installed_pg.changed

  - name: start postgres
    service:
      name: postgresql.service
      state: started
